# Generated by Django 5.2.5 on 2025-08-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['session_id', 'created_at'], name='chat_conver_session_cf61b8_idx'),
        ),
    ]
